//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.06 at 12:17:38 PM CST
//

package games.closetmonster.trpg.storywriter.xml.routes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for directionType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="directionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="North"/>
 *     &lt;enumeration value="Northwest"/>
 *     &lt;enumeration value="West"/>
 *     &lt;enumeration value="Southwest"/>
 *     &lt;enumeration value="South"/>
 *     &lt;enumeration value="Southeast"/>
 *     &lt;enumeration value="East"/>
 *     &lt;enumeration value="Northeast"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "directionType")
@XmlEnum
public enum DirectionType {

	@XmlEnumValue("North")
    NORTH("North"),
    @XmlEnumValue("Northwest")
    NORTHWEST("Northwest"),
    @XmlEnumValue("West")
    WEST("West"),
    @XmlEnumValue("Southwest")
    SOUTHWEST("Southwest"),
    @XmlEnumValue("South")
    SOUTH("South"),
    @XmlEnumValue("Southeast")
    SOUTHEAST("Southeast"),
    @XmlEnumValue("East")
    EAST("East"),
    @XmlEnumValue("Northeast")
    NORTHEAST("Northeast");

	private final String value;

	DirectionType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static DirectionType fromValue(String v) {
		for (DirectionType c : DirectionType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
