//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.06 at 12:17:38 PM CST
//

package games.closetmonster.trpg.storywriter.xml.routes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for requiredItemType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="requiredItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *       &lt;/sequence>
 *       &lt;attribute name="itemConsumed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requiredItemType", propOrder = { "itemId" })
public class RequiredItemType {

	@XmlElement(required = true, nillable = true)
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object itemId;
	@XmlAttribute(name = "itemConsumed", required = true)
	protected boolean itemConsumed;

	/**
	 * Gets the value of the itemId property.
	 *
	 * @return possible object is {@link Object }
	 *
	 */
	public Object getItemId() {
		return itemId;
	}

	/**
	 * Sets the value of the itemId property.
	 *
	 * @param value
	 *            allowed object is {@link Object }
	 *
	 */
	public void setItemId(Object value) {
		this.itemId = value;
	}

	/**
	 * Gets the value of the itemConsumed property.
	 *
	 */
	public boolean isItemConsumed() {
		return itemConsumed;
	}

	/**
	 * Sets the value of the itemConsumed property.
	 *
	 */
	public void setItemConsumed(boolean value) {
		this.itemConsumed = value;
	}

}
