//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.06 at 12:17:38 PM CST
//

package games.closetmonster.trpg.storywriter.xml.routes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for routeType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="routeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromLocationId" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="direction" type="{http://www.closetmonster.games/trpg/storywriter/xml/routes}directionType"/>
 *         &lt;element name="toLocationId" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="lock" type="{http://www.closetmonster.games/trpg/storywriter/xml/routes}lockType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "routeType", propOrder = { "fromLocationId", "direction", "toLocationId", "lock" })
public class RouteType {

	@XmlElement(required = true, nillable = true)
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object fromLocationId;
	@XmlElement(required = true, nillable = true)
	@XmlSchemaType(name = "string")
	protected DirectionType direction;
	@XmlElement(required = true, nillable = true)
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object toLocationId;
	protected LockType lock;
	@XmlAttribute(name = "id", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;

	/**
	 * Gets the value of the fromLocationId property.
	 *
	 * @return possible object is {@link Object }
	 *
	 */
	public Object getFromLocationId() {
		return fromLocationId;
	}

	/**
	 * Sets the value of the fromLocationId property.
	 *
	 * @param value
	 *            allowed object is {@link Object }
	 *
	 */
	public void setFromLocationId(Object value) {
		this.fromLocationId = value;
	}

	/**
	 * Gets the value of the direction property.
	 *
	 * @return possible object is {@link DirectionType }
	 *
	 */
	public DirectionType getDirection() {
		return direction;
	}

	/**
	 * Sets the value of the direction property.
	 *
	 * @param value
	 *            allowed object is {@link DirectionType }
	 *
	 */
	public void setDirection(DirectionType value) {
		this.direction = value;
	}

	/**
	 * Gets the value of the toLocationId property.
	 *
	 * @return possible object is {@link Object }
	 *
	 */
	public Object getToLocationId() {
		return toLocationId;
	}

	/**
	 * Sets the value of the toLocationId property.
	 *
	 * @param value
	 *            allowed object is {@link Object }
	 *
	 */
	public void setToLocationId(Object value) {
		this.toLocationId = value;
	}

	/**
	 * Gets the value of the lock property.
	 *
	 * @return possible object is {@link LockType }
	 *
	 */
	public LockType getLock() {
		return lock;
	}

	/**
	 * Sets the value of the lock property.
	 *
	 * @param value
	 *            allowed object is {@link LockType }
	 *
	 */
	public void setLock(LockType value) {
		this.lock = value;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setId(String value) {
		this.id = value;
	}

}
