//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.06 at 12:17:38 PM CST
//

package games.closetmonster.trpg.storywriter.xml.locations;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * games.closetmonster.trpg.storywriter.xml.locations package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Locations_QNAME = new QName(
			"http://www.closetmonster.games/trpg/storywriter/xml/locations", "locations");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * games.closetmonster.trpg.storywriter.xml.locations
	 *
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link LocationsType }
	 *
	 */
	public LocationsType createLocationsType() {
		return new LocationsType();
	}

	/**
	 * Create an instance of {@link LocationType }
	 *
	 */
	public LocationType createLocationType() {
		return new LocationType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link LocationsType }
	 * {@code >}}
	 *
	 */
	@XmlElementDecl(namespace = "http://www.closetmonster.games/trpg/storywriter/xml/locations", name = "locations")
	public JAXBElement<LocationsType> createLocations(LocationsType value) {
		return new JAXBElement<LocationsType>(_Locations_QNAME, LocationsType.class, null, value);
	}

}
